In [15]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
from pandas import Series, DataFrame

In [16]:
data = pd.read_excel('population_projection.xls',skiprows=1)

In [17]:
data.head()

,STATE,POPULATION (2006),ANNUAL % GR,ANNUAL G.R,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,ABIA,2845380,2.7,0.027,2.923252e+06,3.003255e+06,3.085447e+06,3.169889e+06,3.256642e+06,3.345769e+06,3.437336e+06,3.531408e+06,3.628055e+06,3.727347e+06
1,ADAMAWA,3178950,2.9,0.029,3.272489e+06,3.368781e+06,3.467906e+06,3.569948e+06,3.674992e+06,3.783127e+06,3.894444e+06,4.009037e+06,4.127001e+06,4.248436e+06
2,AKWA/IBOM,3902051,3.4,0.034,4.037002e+06,4.176620e+06,4.321067e+06,4.470509e+06,4.625120e+06,4.785078e+06,4.950568e+06,5.121781e+06,5.298916e+06,5.482177e+06
3,ANAMBRA,4177828,2.8,0.028,4.296460e+06,4.418461e+06,4.543926e+06,4.672954e+06,4.805646e+06,4.942106e+06,5.082440e+06,5.226760e+06,5.375177e+06,5.527809e+06
4,BAUCHI,4653066,3.4,0.034,4.813990e+06,4.980480e+06,5.152728e+06,5.330933e+06,5.515302e+06,5.706046e+06,5.903388e+06,6.107554e+06,6.318781e+06,6.537314e+06

In [28]:
obj = pd.Series([1,2,3,4],index=['a', 'b', 'c', 'd'])

In [35]:
ind = obj.index

In [36]:
ind[0]

'a'

In [30]:
obj.values

array([1, 2, 3, 4], dtype=int64)

In [34]:
type(data.columns)

pandas.core.indexes.base.Index

In [37]:
index = data.columns

In [38]:
index

Index([            'STATE', 'POPULATION (2006)',       'ANNUAL % GR',
              'ANNUAL G.R',                2007,                2008,
                      2009,                2010,                2011,
                      2012,                2013,                2014,
                      2015,                2016],
      dtype='object')

In [67]:
index = [ x.replace(' ','') for x in index]

In [68]:
data.columns = index

In [69]:
data.columns

Index(['STATE', 'POPULATION(2006)', 'ANNUAL%GR', 'ANNUALG.R', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'],
      dtype='object')

In [71]:
data.drop(columns = ['ANNUAL%GR','ANNUALG.R'], inplace = True)

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 12 columns):
STATE               38 non-null object
POPULATION(2006)    38 non-null int64
2007                38 non-null float64
2008                38 non-null float64
2009                38 non-null float64
2010                38 non-null float64
2011                38 non-null float64
2012                38 non-null float64
2013                38 non-null float64
2014                38 non-null float64
2015                38 non-null float64
2016                38 non-null float64
dtypes: float64(10), int64(1), object(1)
memory usage: 3.6+ KB

In [74]:
data.isnull()

,STATE,POPULATION(2006),2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False